# See https://golangci-lint.run/usage/configuration/ for reference
# or https://github.com/golangci/golangci-lint/blob/main/.golangci.reference.yml
version: 2

run:
  go: '1.24'
  timeout: 5m
  modules-download-mode: readonly
  relative-path-mode: gomod

formatters:
  enable:
#    - gci
    - gofmt
#    - gofumpt
    - goimports
#    - golines

linters-settings:
  gofmt:
    simplify: true

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - ineffassign
    - misspell
    - staticcheck
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0 