# See https://golangci-lint.run/usage/configuration/ for reference
# or https://github.com/golangci/golangci-lint/blob/main/.golangci.reference.yml
version: "2"

run:
  go: '1.24'
  timeout: 5m
  modules-download-mode: readonly
  relative-path-mode: gomod

formatters:
  enable:
    - gofmt
    - goimports
    - golines
  settings:
    gofmt:
      simplify: true
    golines:
      max-len: 200

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
    - whitespace

issues:
  max-issues-per-linter: 0
  max-same-issues: 0 