name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [amd64, arm64]
        exclude:
          # Exclude arm64 builds on ubuntu for now
          - os: ubuntu-latest
            arch: arm64
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        cache: true

    - name: Run tests
      run: make test

    - name: Set binary name
      id: binary
      run: |
        os_name=$(echo ${{ runner.os }} | tr '[:upper:]' '[:lower:]')
        echo "name=educates-${os_name}-${{ matrix.arch }}" >> $GITHUB_OUTPUT

    - name: Build
      run: |
        GOARCH=${{ matrix.arch }} make build
        mv bin/educatesenv bin/${{ steps.binary.outputs.name }}

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.binary.outputs.name }}
        path: bin/${{ steps.binary.outputs.name }}
        retention-days: 10 