name: Build Binaries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build (${{ matrix.os }}-${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
            runner: ubuntu-latest
          - os: linux
            arch: arm64
            runner: ubuntu-latest
          - os: darwin
            arch: amd64
            runner: macos-latest
          - os: darwin
            arch: arm64
            runner: macos-latest
          - os: windows
            arch: amd64
            runner: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Set up environment variables
        run: |
          echo "GOOS=${{ matrix.os }}" >> $GITHUB_ENV
          echo "GOARCH=${{ matrix.arch }}" >> $GITHUB_ENV
        shell: bash

      - name: Build binary
        run: |
          mkdir -p dist
          if [ "${{ matrix.os }}" = "windows" ]; then
            go build -o dist/educatesenv-${{ matrix.os }}-${{ matrix.arch }}.exe .
          else
            go build -o dist/educatesenv-${{ matrix.os }}-${{ matrix.arch }} .
          fi
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: educatesenv-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            dist/educatesenv-${{ matrix.os }}-${{ matrix.arch }}* 