name: golangci-lint

on:
  push:
    branches:
      - develop
      - main

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.1.5
          args: -v