name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      # packages: write
      # issues: write
      # id-token: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        cache: true

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        # 'latest', 'nightly', or a semver
        version: "~> v2"
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # The base64 of the contents of your '.p12' key.
        MACOS_SIGN_P12: ${{ secrets.MACOS_SIGN_P12 }}
        # The password to open the '.p12' key.
        MACOS_SIGN_PASSWORD: ${{ secrets.MACOS_SIGN_PASSWORD }}
        # The base64 of the contents of your '.p8' key.
        MACOS_NOTARY_KEY: ${{ secrets.MACOS_NOTARY_KEY }}
        # The ID of the '.p8' key.
        # You can find it in the filename, as well as the Apple Developer Portal
        # website.
        MACOS_NOTARY_KEY_ID: ${{ secrets.MACOS_NOTARY_KEY_ID }}
        # The issuer UUID.
        # You can find it in the Apple Developer Portal website.
        MACOS_NOTARY_ISSUER_ID: ${{ secrets.MACOS_NOTARY_ISSUER_ID }}        